#!/bin/bash
git rm   ChangeLog
git rm   autogen.sh
git rm   build-aux/compile
git rm   build-aux/depcomp
git rm   build-aux/install-sh
git rm   build-aux/ltmain.sh
git rm   build-aux/missing
git rm   compile
git rm   config.h.in
git rm   debian/autogen.sh
git rm   debian/compat
git rm   debian/libmnl-dev.dirs
git rm   debian/libmnl/opt/vyatta/include/libmnl/libmnl.h
git rm   debian/libmnl/opt/vyatta/lib/pkgconfig/libmnl.pc
git rm   debian/libmnl/usr/share/lintian/overrides/libmnl
git rm   debian/libmnl0.dirs
git rm   debian/lintian
git rm   depcomp
git rm   examples/Makefile.in
git rm   examples/genl/.gitignore
git rm   examples/genl/Makefile.in
git rm   examples/netfilter/.gitignore
git rm   examples/netfilter/Makefile.in
git rm   examples/rtnl/.gitignore
git rm   examples/rtnl/Makefile.in
git rm   include/Makefile.in
git rm   include/libmnl/Makefile.in
git rm   include/linux/Makefile.in
git rm   install-sh
git rm   ltmain.sh
git rm   m4/.gitignore
git rm   missing
git rm   src/Makefile.in
